# vim: ft=ansible :
---
- name: Initialize datadir
  shell: "/usr/bin/mysql_install_db --user={{ mariadb_daemon_user }} --datadir={{ galera_mysql_datadir }}"
  args:
    creates: "{{ galera_mysql_datadir }}/mysql"
  register: mysql_install_db
  when:
    - inventory_hostname == galera_bootstrap_node

- name: Kill MariaDB after first run.
  command: |
    "/usr/bin/pkill -9 {{ mariadb_daemon }}"
  when:
    - mysql_install_db.changed

- name: Ensure MariaDB is started and enabled on boot.
  service:
    name: "{{ mariadb_daemon }}"
    state: started
    enabled: yes

- name: Adding Galera Configuration.
  template:
    src: galera.cnf.j2
    dest: "{{ mariadb_config_dir }}/galera.cnf"
    owner: root
    group: root
    mode: 0644
  register: galera_config