# vim: ft=ansible :
---
# tasks file secure
- name: Ensure MariaDB is started and enabled on boot.
  service:
    name: "{{ mariadb_daemon }}"
    state: started
    enabled: yes
  when: inventory_hostname == galera_bootstrap_node

- name: Remove anonymous MySQL users.
  mysql_user:
    name: ""
    host_all: yes
    state: absent
  when: inventory_hostname == galera_bootstrap_node
  run_once: true

- name: Remove MySQL test database.
  mysql_db:
    name: "test"
    state: absent
  when: inventory_hostname == galera_bootstrap_node
  run_once: true

- block:
  - name: Update MySQL root password for all host.
    mysql_user:
      name: "root"
      password: "{{ mariadb_root_password }}"
      host_all: yes
  rescue:
  - name: Update MySQL root password for all host.
    mysql_user:
      login_user: "{{ mariadb_root_username }}"
      login_password: "{{ mariadb_root_password }}"
      name: "{{ mariadb_root_username }}"
      password: "{{ mariadb_root_password }}"
      host_all: yes
  run_once: true
  when: inventory_hostname == galera_bootstrap_node

# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "~/.my.cnf"
    owner: root
    group: root
    mode: 0600
